### ISSUE TITLE
🐛 [bug] Resurrect in the demo fires a fireball

### ISSUE THREAD

**Issue by sh1ny** [OctoD/godot-gameplay-systems#11]
**Describe the bug**
Pressing the R button for resurrect also fires a fireball in the demo

**To Reproduce**
1. Open the project
2. Run the project
3. Grab the fireball
4. Die somehow
5. Press R to resurrect
6. Keep pressing R, notice the debug messages

**Expected behavior**
Abilities shouldn't activate each other

**Screenshots**
No screenshot needed.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Godot version : 4.0.2

**Additional context**
100% reproducable

**Comment by OctoD** [comment]
Fixed, I did it wrong when setupping the example, thank you for reporting!
