### ISSUE TITLE
🐛 [bug] Installation is not working as expected

### ISSUE THREAD

**Issue by DavidOcacho** [OctoD/godot-gameplay-systems#14]
**Describe the bug**
The installation process you mention on the README doesn't work as expected due to folder organization

**To Reproduce**
1. Clone the repository in your addons folder
2. Try to enable it

**Expected behavior**
I'd like to clone the repository inside the folder and be able to enable the plugin without errors

**Screenshots**
![image](https://user-images.githubusercontent.com/126606809/234857515-820d7e2f-fdac-41f3-96ab-87ee660ec7c0.png)

This is gonna fail because if you clone the repo on your addons your path is the following:
`addons\godot_gameplay_systems\addons\godot_gameplay_systems`

I can create a fork and change this but I think is worth to mention since it's not a big change and it's blocking the usage of the plugin in a straight-forward way.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Godot version: 4.0.2

**Additional context**
Thanks for your time!

**Comment by OctoD** [comment]
You are right, I am fixing the docs, thank you!
