### ISSUE TITLE
🐛 [bug] Pickable_item_3d can not add if inventory is assigned to collider node(player)

### ISSUE THREAD

**Issue by Sezotove** [OctoD/godot-gameplay-systems#26]
**Describe the bug**
Player has Inventory and Equipment. Added Pickable_Area_3d with item and auto_pickup. When player collides the following error is thrown:

`Invalid type in function 'can_add' in base 'Node (Inventory)'. The Object-derived class of argument 1 (Node (Inventory)) is not a subclass of the expected argument class.`

This appears to happen because in lines 53-56 as shown below, it's passing the 'by' node to it's self, which fails as inventory.can_add() is expecting the argument to be of type Item:

```
func pick(by: Node) -> void:
	assert(item != null, "item should not be null")

	if by is Inventory:
		if by.can_add(by):
			by.add_item(by)
			queue_free()
	elif by is Equipment:
		## Adds tags because it "picked" the item.
		by.add_tags(item.tags_added_on_add)
```

```
func can_add(item: Item) -> bool:
	if item.tags_required_to_add.size() == 0:
		return true

	for tag in item.tags_required_to_add:
		if not tags.has(tag):
			return false

	return true
```

**To Reproduce**
1) Open Doom-Like Demo player.
2) Add Inventory to player.
3) Play game and select Doom-Like Demo.
4) Run over weapon, it should throw the reported error.

**Expected behavior**
Item gets added to the inventory.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: WIN11
 - Godot version 4.0.3

**Additional context**
N/A

**Comment by Sezotove** [comment]
So changing:

```
if by is Inventory:
		if by.can_add(by):
			by.add_item(by)
			queue_free()
```

to:

```
if by is Inventory:
		if by.can_add(item):
			by.add_item(item)
			queue_free()
```

resolves this.

**Comment by OctoD** [comment]
Yup, fixed both for 2D and 3D nodes, thank you!
