### ISSUE TITLE
🐛 [bug] GameplayAttributeMap Bugs

### ISSUE THREAD

**Issue by ywmaa** [OctoD/godot-gameplay-systems#37]
**Describe the bug**

**To Reproduce**

Add A GameplayAttributeMap
Look at the inspector for it.
You will see only Attributes Variable, and it uses the type Attribute Table LOL.
the attribute table doesn't show up.
also assigning attribute table resource to it, doesn't allow me to add a health or something (I following your tutorial).

I changed this section
```
## Is the array of Attribute resources generated by the inspector plugin.
@export var attributes: Array[AttributeResource] 

## Is the AttributeTable selected resource.
@export var table: AttributeTable 
```
To
```
## Is the array of Attribute resources generated by the inspector plugin.
@export var Attributes: Array[AttributeResource] 

## Is the AttributeTable selected resource.
@export var Table: AttributeTable 
```
and it show them seperately
![image](https://github.com/OctoD/godot-gameplay-systems/assets/68971808/09eabc4d-3566-465d-983a-5a53e5f40444)

but as seen it doesn't create a resource attribute manually, I need to do it myself : 
![image](https://github.com/OctoD/godot-gameplay-systems/assets/68971808/8adc5a76-5a02-4dab-8e82-5a76bc53e56e)

**Expected behavior**
Working Out Of The Box, lol :)

**Screenshots**
![image](https://github.com/OctoD/godot-gameplay-systems/assets/68971808/be529192-c370-466d-892f-5f20050b51ef)

**Desktop (please complete the following information):**
 - OS: Linux
 - Godot version 4.2.dev4

**Additional context**
N/A

**Comment by OctoD** [comment]
Hello! Thanks for using ggs and for reporting! May I ask you to give me a small repo so I can debug it properly? Thank you in advance!
