### ISSUE TITLE
🐛 [bug] Cooldown invalid.

### ISSUE THREAD

**Issue by Abab-bk** [OctoD/godot-gameplay-systems#43]
Needless to say, create an Ability, then set the cooldown, which will be reactivated if I call activate () .

**Comment by Abab-bk** [comment]
Like "
https://github.com/OctoD/godot-gameplay-systems/blob/main/docs/ability-system.md"
said.
(I'm just following the documentation)
I created a script that creates an extension class Ability.
And wrote the activate() method.
Then I set its cooldown to 3.0 in the inspector.
When I tried calling activate() multiple times, it took effect, completely
ignoring the 3.0 cooldown I had set.
Would appreciate it if you could look into this.

OctoD ***@***.***> 于2023年10月16日周一 20:58写道：

**Comment by OctoD** [comment]
Did you try to add a tag to `Cooldown Start` and `To Remove On Cooldown End` ability properties? 
(If you are creating the ability programmatically these properties can be set by code as `tags_cooldown_start` and`tags_to_remove_on_cooldown_end`. 

This part is actually missing from the docs, maybe this should fix the issue.

You can see them in action in `res://examples/simple_2d_platformer/player/player.tscn`, clicking on the `AbilityContainer` node and then browsing the assigned abilities.

Thank you!

**Comment by Abab-bk** [comment]
ok, thanks.
