### ISSUE TITLE
🐛 [bug] Ability Container Array[Ability] Order is Reversed

### ISSUE THREAD

**Issue by tlifke** [OctoD/godot-gameplay-systems#49]
**Describe the bug**
When creating new abilities and putting them into the Ability Container's Ability Array, the resulting order seems to be reversed. The UI below indicates an array with the following order:

1. "Regenerate"
2. "Sacrifice"
3. Ability with ui_name "fake_pos2"
4.  Ability with ui_name "fake_pos3". 

The latter two abilities are dummies which have ui_names indicating the expected position in the array. You can see this ordering reflecting in the following screenshot.

<img width="414" alt="Screenshot 2023-12-17 at 3 08 22 PM" src="https://github.com/OctoD/godot-gameplay-systems/assets/29410053/c2ce79ba-0123-4f49-9382-7690dd0c2089">

However, when I attempt to active Regenerate using the following code
```
var ability = ability_container.granted_abilities[0]
ability_container.activate_one(ability)
```
it instead activates the "fake_pos3" ability (or it would if it weren't a placeholder). When we print the array using the following code:
```
for idx in len(ability_container.granted_abilities):
	print(idx,ability_container.granted_abilities[idx].ui_name)
```
We would expect to see the index printed along the ability ui_name associated with the index. Instead we see the following screenshot:

<img width="255" alt="Screenshot 2023-12-17 at 3 08 31 PM" src="https://github.com/OctoD/godot-gameplay-systems/assets/29410053/4bd00da9-d68c-4858-81ae-9230cca6d095">

In the screenshot, the order is reversed relative to the expectation.

**To Reproduce**
1. Initialize a character and add a GameplayAttributes with a GameplayEffect as its child. Also add an AbilityContainer. My tree looks like this: 
<img width="270" alt="Screenshot 2023-12-17 at 3 09 25 PM" src="https://github.com/OctoD/godot-gameplay-systems/assets/29410053/3730fe18-13d9-4d61-b096-663e75213956">
2. Add at least two Abilities to the AbilityContainer. I chose to add 4 to verify the behavior.
3. Attach a script to the player and retrieve the AbilityContainer and AttributeMap.
4. In the script, identify the contents of the AbilityContainer's granted_abilities[Ability] array. I used the following code:
```

func _input(event):
    if event.is_action_pressed("ability_q"):
        for idx in len(ability_container.granted_abilities):
	    print(idx,ability_container.granted_abilities[idx].ui_name)
```
In my case, this yields output of 
0Fake_pos3
1fake_pos2
2Sacrifice
3Regenerate

**Expected behavior**
I would expect the output instead to be:
0Regenerate
1Sacrifice
2fake_pos2
3Fake_pos3

**Screenshots**
Included inline

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.1
 - Godot version 4.1.3

**Additional context**
I've found a fairly simple fix for my case. In ability_container.gd, add `granted_abilities.reverse()` to the function after granting the abilities, i.e.
```
func _ready() -> void:
	gameplay_attribute_map = get_node(gameplay_attribute_map_path)
	grant_all_abilities()
	granted_abilities.reverse()
```

However, this may not fix the issue when abilities are appended to the array as a part of the game, i.e. not a runtime. I suspect the issue lies in grant() or in grant_all_abilities(), but I'm still a bit new to Godot and am not 100% sure where the issue is arising. My best guess is that in grant_all_abilities(), when iterating through the abilities it grants them in reverse order because cursor is set to -1. When I add print statements to the function

```func grant_all_abilities() -> int:
	var granted = 0
	var cursor = -1

	for i in abilities.size():

		var ability = abilities[cursor]
		for ab in abilities:
			print(ab.ui_name)
		print(i,cursor,ability.ui_name)
		if grant(ability):
			granted += 1
		else:
			cursor -= 1

	return granted
```
It yields the following:
```
Regenerate
Sacrifice
fake_pos2
Fake_pos3
0-1Fake_pos3
Regenerate
Sacrifice
fake_pos2
1-1fake_pos2
Regenerate
Sacrifice
2-1Sacrifice
Regenerate
3-1Regenerate
```

It seems to grant from the back of the abilities array first when granting, making it so Regenerate is added last despite being listed first. It might be that iterating in a different way would correct the ordering, but it may be that you have a reason for iterating in this way and I'm still new enough to Godot that I'm unsure the proper way.

**Reproducible project**
Here's the link to my [project.](https://github.com/tlifke/LastStar) The relevant files are archetype_base.gd in the root directory and the ability_container.gd script found in the addons folder.

**Comment by OctoD** [comment]
Hello! Thank you for reporting! I will look into this one asap! Thank you for your patience!

**Comment by tlifke** [comment]
Sure thing! Loving the system so far, you've clearly put in a ton of work. Let me know if there's anything I do to help out!

**Comment by OctoD** [comment]
To get a specific ability, may I ask you to try with this code?

```gdscript
var ability = ability_container.find_by(func (ability): return ability is Regenerate)
# ... do whatever it should do it
```

It's already built-in in the `AbilityContainer` node.

Abilities are granted from back to start because granting an ability will remove it from the initial array (aka the editable one).

Thank you!

**Comment by tlifke** [comment]
That's a much better way of accessing the ability, thanks for pointing it out. I'll convert to doing it that way.

Thanks for the swift response and your patience with my learning!
