### ISSUE TITLE
Comments and actual code is different

### ISSUE THREAD

**Issue by Ariyn** [OctoD/godot-gameplay-systems#9]
https://github.com/OctoD/godot-gameplay-systems/blob/32312eb92e2c3d4b748f5bccaef5d9c4702b3c3a/addons/godot_gameplay_systems/resources/ability.gd#L113-L119

Comments says `Always return: true if Ability.tags_end_blocking is empty`, but this function returns false.
`can_cancel`, `can_block` return false too.

Is comment wrong or code wrong? 

PS. this wonderful library saved my life. thx! XP

**Comment by OctoD** [comment]
The implementation is wrong, sorry, I wrote it in a rush. I'll fix it asap, thank you!

By the way, more has to come, I am implementing a general purpose inventory system along with other gameplay mechanics, thank you for using it!
